CXX = g++
CXXFLAGS = -g

default: search average mystery

search: search.cpp
	${CXX} ${CXXFLAGS} search.cpp -o search

average: average.cpp
	${CXX} ${CXXFLAGS} average.cpp -o average

mystery: mystery.cpp
	${CXX} ${CXXFLAGS} mystery.cpp -o mystery

clean: 
	rm -f *.o search average mystery
